import * as vscode from 'vscode';

// startDraftMode: generates the readme file based on the following logic
//	1. checks if README.md file exists
//	2. if not, create it 
//	3. creates the draft, and waits for confirmation in "applyDraftMode"
export async function startDraftMode() {
	const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders) {
        vscode.window.showErrorMessage('SubText: Please open a folder first.');
        return;
    }

	const rootPath = workspaceFolders[0].uri;
    // Define the path to README.md in the root
    const readmeUri = vscode.Uri.joinPath(rootPath, 'README.md');

	// Generating Content 
	// currently mock content, will be replaced by LLM generated content 
	const initialContent = 
		`# Project: ${workspaceFolders[0].name}

## Overview
This project is a [insert description] built with [tech stack].

## Features
- [ ] Feature 1
- [ ] Feature 2

## Installation
\`\`\`bash
npm install
npm run start
\`\`\`

## Auto-Generated by SubText
*Draft generated at ${new Date().toLocaleTimeString()}*
`;
	
	// Open preview 
	// will open as "untitled" so it doesn't save automatically 
	const draftDoc = await vscode.workspace.openTextDocument({
		content: initialContent,
		language: 'markdown'
	});

	// show the file 
	await vscode.window.showTextDocument(draftDoc, {
		viewColumn: vscode.ViewColumn.Beside,
		preview: false
	});

	// enable "draft mode"
	await vscode.commands.executeCommand('setContext', 'subtext.isDrafting', true);
}

// applyDraftMode: saves content, kills the draft, resets context
export async function applyDraftMode() {
	const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders) {
        vscode.window.showErrorMessage('SubText: No open folder found to save to.');
        return;
    }

	const targetUri = vscode.Uri.joinPath(workspaceFolders[0].uri, 'README.md');

	// get text from current editor
	const editor = vscode.window.activeTextEditor;
	if (!editor) {return; } // editor doesn't exist

	if (editor.document.isUntitled === false) {
        vscode.window.showWarningMessage('SubText: You are not editing a draft!');
        return;
    }

	const finalContent = editor.document.getText();
	const data = new TextEncoder().encode(finalContent);

	// Write to the README file
	try {
		await vscode.workspace.fs.writeFile(targetUri, data);
		vscode.window.showInformationMessage('✅ README updated!');
	} catch (err) {
        vscode.window.showErrorMessage('Failed to write README');
    }

	// Closes the draft
	await vscode.commands.executeCommand('workbench.action.revertAndCloseActiveEditor');

	// Turn off draft mode
	await vscode.commands.executeCommand('setContext', 'subtext.isDrafting', false);

	// Open real file to confirm 
	const realDoc = await vscode.workspace.openTextDocument(targetUri);
    await vscode.window.showTextDocument(realDoc);
}